FROM alpine:latest AS envsubst
RUN apk add --no-cache gettext
COPY config/gorse.toml /tmp/gorse.toml.template
ARG GORSE_CACHE_STORE
ARG GORSE_DATA_STORE
ARG GORSE_DASH_USER_NAME
ARG GORSE_DASH_PASSWORD
ARG GORSE_API_KEY
ARG GORSE_ADMIN_API_KEY
RUN envsubst < /tmp/gorse.toml.template > /tmp/gorse.toml

FROM zhenghaoz/gorse-in-one
WORKDIR /app
COPY --from=envsubst /tmp/gorse.toml /app/config/gorse.toml
CMD ["gorse-in-one", "-c", "/app/config/gorse.toml"]
